### PR TITLE
Api Wrapper

### PR DESCRIPTION
**Pull request by serge20**

### CODE REVIEW

**Comment by DoraLee000** [comment]
Hello Serge Basile

I appreciated your time and effort
But I don't know, in the Pagination component, onChangeEventy function add
router.push ({
pathname: '/', Query: {page: event}}),
req.query is still {} without any value, but I can get req.headers.
Referer, can you tell me what I did wrong ?




Looking forward to your reply

Serge Basile <notifications@github.com>於 2020年3月30日 週一，上午4:21寫道：

**Comment by serge20** [comment]
Hey, It's a bit difficult for me to see what you're doing, can you create a PR so that I can see what you're doing. One thing i can say is have you tried using "query" vs Query? Also when you push does the route update with the query in the url? 

You can see this example here: https://codesandbox.io/s/quizzical-frog-hhtig

**Comment by DoraLee000** [comment]
Hey Serge Basile



First of all, the Api Wrapper can fetch data successfully in client-side
render,

But I have the following three questions


1.If the data cannot be retrieved successfully when server-side render is
applied
I expect to be at the URL "http://localhost:1010/? Page =1" fetch API to
fetch page=1 data and display it on the screen

When I change the pagination get the value change the URL? Page =2,
redispatch (updateData(event))



2. I import Router from 'next/ Router ', using router.push ({pathname:
'/',query: {page: event},}) in the Pagination component;

ULR successfully changed to "http://localhost:1010/? Page =2",
but req.query in the/API /attractions file still does not get the page value



3. /api/attractions/index. Use of js the files?


That's my branch name " feature/0331 "
https://github.com/DoraLee000/travel-blog-next/tree/feature/0331


I hope you can give me some advice and look forward to your reply



Serge Basile <notifications@github.com>於 2020年3月31日 週二，上午3:51寫道：

**Comment by serge20** [comment]
Hey Dora,

So for 1. you were calling fetch("/api/attractions"). On the server side it doesn't know the api to call. So you need to pass the full url, so if you replace that with something like http://localhost:1010/api/attractions it will work. The only problem is that when you deploy to staging or production you will be using a different url, so you would need a way to differentiate between environments for that. 

2. the api folder that should be reading things lives inside the pages folder so it's pages/api/attractions/index.js. "page" is never passed since all you do is trigger the saga method to load the data and that api is always "/api/attractions" which makes sense why page is never defined. You need to be passing that to your fetch method so that it reads it. 

Is there any reason why you're using redux-saga? I'm not sure what you're trying to do but it seems like it's a bit overkill to use for a blog.. I don't see the need to use the store at all either. You should just focus on using hooks with either useState or useReducer, that will be super simple for you.

**Pull request merged**
